### PR TITLE
Release 1.9.88

### PR DESCRIPTION
**Pull request by ghost**
Will this automatically publish to https://mvnrepository.com/ once it gets merged?

### CODE REVIEW

**Comment by vpriesner** [comment]
@thibaultmeyer can you help here? :)

**Comment by raphaelbauer** [comment]
Hi @vpriesner - sorry I am a bit inactive lately. I can push the code soonish to the maven repo.

But please keep in mind that the ninja-appengine library is still kind of experimental :)

**Comment by raphaelbauer** [comment]
Hey @vpriesner the new version should now be available on maven central :)

**Comment by vpriesner** [comment]
Hey @raphaelbauer are you sure about that? 🤔

**Comment by raphaelbauer** [comment]
Hmm. you are right. It's not yet listed on maven central. Let's wait until Monday... Otherwise I have to file a ticket... Thanks for the hint!

**Comment by raphaelbauer** [comment]
Something went wrong but now it should be online soonish - make sure to use version 1.9.88.1

By the way - I am currently not really maintaining this module as the new appengine environment works with ninja out of the box using the command line tools. If you are interested you can consider maintaining this library :)

**Comment by ghost** [comment]
Would you be able to elaborate on "the new appengine environment works with ninja out of the box using the command line tool"?
If we can document this here, maybe this repo can be closed for good?

**Pull request merged**
